### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by superman-enamy** [alexbieber/RevengeBomber2.0#2]
Check Working from your end

**Comment by alexbieber** [comment]
Yeah sure !

**Comment by alexbieber** [comment]
It will run in root permission! Try doin "sudo su " and then run - cd RevengeBomber2.0 ,  bash RevengeBomber2.0.sh !  Hope it will solve your problem . If it doesn't solve your problem then let me know here in the comments ! Thank you!

**Comment by alexbieber** [comment]
read - how to use once more ! Thank You!
