### ISSUE TITLE
running issue 

### ISSUE THREAD

**Issue by foolish99** [alexbieber/RevengeBomber2.0#3]
couldn't run the code on termux
![Uploading Screenshot_20220706_100637.jpg…]()

**Comment by MavericksGooses** [comment]
Doesn't work

**Comment by hackersenu** [comment]
sms not sent

**Comment by Ridoy6979** [comment]
Ki baler tools deo Bangladesh a kaj kore na

**Comment by Ridoy6979** [comment]
My telegram.  @I_M_Ridoy

**Comment by Ridoy6979** [comment]
Plz nok https://t.me/I_M_Ridoy

**Comment by alexbieber** [comment]
Kindly follow each n every step!
